[package]
name = "gex"
version = "0.0.6"
edition = "2021"
authors = [ "Bojan Milevski <bojan@bojanmilevski.com>" ]
description = "An extension installer for Gecko browsers"
readme = "README.md"
keywords = [ "firefox", "extensions" ]
categories = [ "command-line-utilities" ]
license = "GPL-v3.0"
repository = "https://github.com/bojanmilevski/gex"

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'
panic = 'abort'
strip = true

[dependencies]
async-trait = "0.1.74"
clap = { version = "4.3.11", features = ["derive"] }
colored = "2.0.4"
indicatif = "0.17.7"
rayon = "1.8.0"
reqwest = { version = "0.11.18", features = ["json"] }
rust-ini = "0.19.0"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.100"
thiserror = "1.0.43"
tokio = { version = "1.29.1", features = ["full"] }
